# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: ondrasek_hanna@wheatoncollege.edu
author_name: Hanna-Ondrasek
cloud_provider: vercel
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: fullstack

